### ISSUE TITLE
ModuleNotFoundError: No module named 'ops.temporal_shift'

### ISSUE THREAD

**Issue by clelevo** [li-stu-998/MIE-Net#1]
感谢您优秀的工作以及提供的代码，但是我在运行过程中提示
ModuleNotFoundError: No module named 'ops.temporal_shift'
from ops.temporal_shift import make_temporal_pool
我仔细检查了代码，也没有发现temporal_shift以及make_temporal_pool函数。

**Comment by li-stu-998** [comment]
您好，我们的工作确实没用到temporal_shift以及make_temporal_pool函数，这是我们在比较与其他注意模块（复现时）加入进去的，您需要的main.py函数中，注释了该行代码即可“from ops.temporal_shift import make_temporal_pool”。

**Comment by li-stu-998** [comment]
您好，我们的工作确实没用到temporal_shift以及make_temporal_pool函数，这是我们在复现与其他注意模块比较时加入进去的，您需要的main.py函数中，注释了gaihang“from ops.temporal_shift import make_temporal_pool”。
